telegram_token: "6162893726:AAGUopgCowLKBhjUkctcYcOI7hQm7B-th7s"
yoomoney_id: '223071'
yoomoney_token: "live_-VtZxbuG_HclG7z7cy4XvW0RqSEURAATpApGqUIEWH0"
mongo_token: "mongodb+srv://Lyzix:eLTdwatIxXoCzESH@db1.zd0t74q.mongodb.net/?retryWrites=true&w=majority"
n_chat_modes_per_page: 5

PROXY_END_POINT: "193.39.244.26:8000"
USERNAME: "qE9pH6"
PASSWORD: "aLX2j2"